name: australian_headlines

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Environment check'
        uses: actions/checkout@v2
        
      - name: 'Setup Java'
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      
      - name: 'Setup Flutter stable version'
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # or: 'dev' or 'beta'
    
      - run: flutter pub get
#       - run: flutter test
      - run: flutter build apk --release
      
      - name: 'print GITHUB_RUN_NUMBER'
        run: echo $GITHUB_RUN_NUMBER
      
#       - name: 'Create a file'
#         run: echo ${{ matrix.node-version }} > ./my_file.txt
      
      - name: 'Upload apk build to artifact'
        uses: actions/upload-artifact@v1
        with:
          name: app-release-v${{github.run_number}}
          path: build/app/outputs/apk/release/app-release.apk
#           path: ./my_file.txt
